### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by maplepy** [robertnunn/DRG-Save-Editor#32]
Since you seem to be using only Python with PyQT5 and PySide2 which are all usable on Linux, would you be interested in making a linux version out of it? or at least able to provide some instructions on how to run it from Linux itself? 

I love your editor, fantastic job! If you need help or anything I'd be happy to help!

Rock and Stone brother

**Comment by robertnunn** [comment]
I don't have any plans to make an official linux version, but you should be able to clone the repo, pip install requirements.txt to a virtual env, and run main.py from there. If that doesn't work let me know, but I've largely moved on from this project and will only be doing critical bug fixes for a while longer.

**Comment by maplepy** [comment]
Thing is, there's no requirements.txt :/

And when I try to run it I get this error
```

from fbs_runtime.application_context.PySide2 import ApplicationContext
Import "fbs_runtime.application_context.PySide2" could not be resolved
```

**Comment by robertnunn** [comment]
I thought I had reqs in the repo, but I guess not.
fbs
PyQt5
PySide2
I think you're just missing fbs

**Comment by maplepy** [comment]
Well, got a new error now:

```
Traceback (most recent call last):
  File "/home/maplepy/Programs/Github/DRG-Save-Editor/main.py", line 23, in <module>
    import winreg
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'winreg'
```

**Comment by maplepy** [comment]
```
~/Programs/Github/DRG-Save-Editor ❯ pip install winreg
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement winreg (from versions: none)
ERROR: No matching distribution found for winreg
```

**Comment by robertnunn** [comment]
I'm sorry, I don't know why your venv is not letting you add new packages but winreg is only used in a few spots to pull the steam install path so you should be able to take it out with minimal fuss.

**Comment by maplepy** [comment]
So I could remove the import and anything related to this library if I use linux?

**Comment by robertnunn** [comment]
Yes

**Comment by maplepy** [comment]
```
[maplepy@syrup DRG-Save-Editor]$ python3 -u "/home/maplepy/Github/DRG-Save-Editor/main.py"
Traceback (most recent call last):
  File "/home/maplepy/Github/DRG-Save-Editor/main.py", line 1320, in <module>
    appctext = ApplicationContext()
  File "/home/maplepy/.local/lib/python3.10/site-packages/fbs_runtime/application_context/__init__.py", line 31, in __init__
    self.app
  File "/home/maplepy/.local/lib/python3.10/site-packages/fbs_runtime/application_context/__init__.py", line 54, in app
    result.setApplicationName(self.build_settings['app_name'])
  File "/home/maplepy/.local/lib/python3.10/site-packages/fbs_runtime/application_context/__init__.py", line 65, in build_settings
    return _source.load_build_settings(self._project_dir)
  File "/home/maplepy/.local/lib/python3.10/site-packages/fbs_runtime/application_context/__init__.py", line 127, in _project_dir
    return _source.get_project_dir()
  File "/home/maplepy/.local/lib/python3.10/site-packages/fbs_runtime/_source.py", line 21, in get_project_dir
    raise FbsError(
fbs_runtime.FbsError: Could not determine the project base directory. Was expecting src/main/python.
```

Yeah no it isn't working either

**Comment by maplepy** [comment]
Installed 

- pyside2
- fbs
- PyQt5
